<a href="https://colab.research.google.com/github/Prajwalng2/sl/blob/main/Skill_Lab_Programs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

def compute_tf_idf(documents, vocabulary):
    N = len(documents)  # Number of documents
    V = len(vocabulary)  # Size of the vocabulary

    # Initialize TF matrix (N x V)
    tf = np.zeros((N, V))

    # Build term frequency (TF) matrix
    for i, doc in enumerate(documents):
        words = doc.lower().split()  # Split document into words
        for word in words:
            if word in vocabulary:
                j = vocabulary.index(word)
                tf[i, j] += 1
        tf[i] = tf[i] / len(words)  # Normalize TF by document length

    # Compute Document Frequency (DF)
    df = np.zeros(V)
    for j, term in enumerate(vocabulary):
        df[j] = sum(1 for doc in documents if term in doc.lower().split())

    # Compute Inverse Document Frequency (IDF)
    idf = np.log(N / (df + 1))  # Add 1 to avoid division by zero

    # Compute TF-IDF matrix
    tf_idf = tf * idf  # Element-wise multiplication
    return tf_idf

# Example usage
documents = [
    "cat sat on the mat",
    "dog sat on the log",
    "cat and dog played together"
]

vocabulary = list(set(" ".join(documents).lower().split()))
tf_idf_matrix = compute_tf_idf(documents, vocabulary)

print("Vocabulary:", vocabulary)
print("TF-IDF Matrix:\n", tf_idf_matrix)


Vocabulary: ['the', 'dog', 'cat', 'log', 'together', 'and', 'on', 'mat', 'played', 'sat']
TF-IDF Matrix:
 [[0.         0.         0.         0.         0.         0.
  0.         0.08109302 0.         0.        ]
 [0.         0.         0.         0.08109302 0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.08109302 0.08109302
  0.         0.         0.08109302 0.        ]]


In [4]:
def generate_ngrams(sentence, n):
    words = sentence.lower().split()  # Convert sentence to lowercase and split into words
    ngrams = []
    for i in range(len(words) - n + 1):  # Loop to create n-grams
        ngram = tuple(words[i:i + n])  # Form a tuple of n consecutive words
        ngrams.append(ngram)
    return ngrams

# Example usage:
sentence = "The quick brown fox jumps over the lazy dog."
n = 3
ngrams = generate_ngrams(sentence, n)

print(f"{n}-grams:")
for gram in ngrams:
    print(gram)


3-grams:
('the', 'quick', 'brown')
('quick', 'brown', 'fox')
('brown', 'fox', 'jumps')
('fox', 'jumps', 'over')
('jumps', 'over', 'the')
('over', 'the', 'lazy')
('the', 'lazy', 'dog.')


In [5]:
def compute_trigram_language_model(documents):
    from collections import defaultdict

    # Initialize trigram counts
    trigram_counts = defaultdict(int)
    total_trigrams = 0

    # Process each document to compute trigram counts
    for doc in documents:
        words = doc.lower().split()
        for i in range(len(words) - 2):
            trigram = tuple(words[i:i + 3])  # Extract a trigram
            trigram_counts[trigram] += 1
            total_trigrams += 1

    # Compute trigram probabilities
    trigram_probabilities = {}
    for trigram, count in trigram_counts.items():
        trigram_probabilities[trigram] = count / total_trigrams

    return trigram_probabilities

# Example usage:
documents = [
    "The quick brown fox jumps over the lazy dog",
    "The quick blue fox jumps over the lazy cat",
    "The lazy dog sleeps under the blue sky"
]

trigram_model = compute_trigram_language_model(documents)

print("Trigram Probabilities:")
for trigram, prob in trigram_model.items():
    print(f"{trigram}: {prob}")


Trigram Probabilities:
('the', 'quick', 'brown'): 0.05
('quick', 'brown', 'fox'): 0.05
('brown', 'fox', 'jumps'): 0.05
('fox', 'jumps', 'over'): 0.1
('jumps', 'over', 'the'): 0.1
('over', 'the', 'lazy'): 0.1
('the', 'lazy', 'dog'): 0.1
('the', 'quick', 'blue'): 0.05
('quick', 'blue', 'fox'): 0.05
('blue', 'fox', 'jumps'): 0.05
('the', 'lazy', 'cat'): 0.05
('lazy', 'dog', 'sleeps'): 0.05
('dog', 'sleeps', 'under'): 0.05
('sleeps', 'under', 'the'): 0.05
('under', 'the', 'blue'): 0.05
('the', 'blue', 'sky'): 0.05


In [6]:
import numpy as np

def create_embedding_matrix(corpus, embedding_dim):
    # Preprocessing
    vocabulary = {}
    index = 0
    for sentence in corpus:
        words = sentence.lower().split()
        for word in words:
            if word not in vocabulary:
                vocabulary[word] = index
                index += 1

    V = len(vocabulary)

    # Initialize embedding matrix with random values between 0 and 1
    E = np.random.rand(V, embedding_dim)

    # Create word to index mapping (already done in vocabulary)
    word_to_index = vocabulary

    # Define get_word_vector function
    def get_word_vector(word):
        word = word.lower()
        if word in word_to_index:
            idx = word_to_index[word]
            return E[idx]
        else:
            return np.zeros(embedding_dim)

    return E, vocabulary, get_word_vector

# Example usage:
corpus = [
    "I love machine learning",
    "Machine learning is amazing",
    "I love learning new things"
]
embedding_dim = 3

# Create embedding matrix and supporting structures
E, vocabulary, get_word_vector = create_embedding_matrix(corpus, embedding_dim)

print("Vocabulary:", vocabulary)
print("Embedding Matrix E:\n", E)

# Test get_word_vector
word = "learning"
vector = get_word_vector(word)
print(f"Embedding for '{word}':", vector)

# Test with a word not in the vocabulary
word = "unknown"
vector = get_word_vector(word)
print(f"Embedding for '{word}':", vector)


Vocabulary: {'i': 0, 'love': 1, 'machine': 2, 'learning': 3, 'is': 4, 'amazing': 5, 'new': 6, 'things': 7}
Embedding Matrix E:
 [[0.43424288 0.7058978  0.38601959]
 [0.86537809 0.37753575 0.63635562]
 [0.78650326 0.5444907  0.03288972]
 [0.21495396 0.60890938 0.38330596]
 [0.87393129 0.93176684 0.51772595]
 [0.64238237 0.57207472 0.31239986]
 [0.21528063 0.1502287  0.3641095 ]
 [0.52305078 0.2292095  0.01370816]]
Embedding for 'learning': [0.21495396 0.60890938 0.38330596]
Embedding for 'unknown': [0. 0. 0.]


In [7]:
import numpy as np

def create_embedding_matrix_with_pretrained(corpus, pretrained_embeddings, embedding_dim):
    # Preprocessing
    vocabulary = {}
    index = 0
    for sentence in corpus:
        words = sentence.lower().split()
        for word in words:
            if word not in vocabulary:
                vocabulary[word] = index
                index += 1

    V = len(vocabulary)

    # Initialize embedding matrix
    E = np.zeros((V, embedding_dim))

    # Assign embeddings
    for word, idx in vocabulary.items():
        if word in pretrained_embeddings:
            E[idx] = np.array(pretrained_embeddings[word])
        else:
            E[idx] = np.random.rand(embedding_dim)  # Random initialization

    # Define get_word_vector function
    def get_word_vector(word):
        word = word.lower()
        if word in vocabulary:
            idx = vocabulary[word]
            return E[idx]
        else:
            return np.zeros(embedding_dim)

    return E, vocabulary, get_word_vector

# Example usage:
corpus = [
    "I love machine learning",
    "Machine learning is amazing",
    "I love learning new things"
]

pretrained_embeddings = {
    "machine": [0.1, 0.2, 0.3],
    "learning": [0.2, 0.3, 0.4],
    "amazing": [0.3, 0.4, 0.5],
    "love": [0.4, 0.5, 0.6]
}

embedding_dim = 3

E, vocabulary, get_word_vector = create_embedding_matrix_with_pretrained(
    corpus, pretrained_embeddings, embedding_dim
)

print("Vocabulary:", vocabulary)
print("Embedding Matrix E:\n", E)

# Test get_word_vector
word = "machine"
vector = get_word_vector(word)
print(f"Embedding for '{word}':", vector)

word = "i"
vector = get_word_vector(word)
print(f"Embedding for '{word}':", vector)  # Randomly initialized

word = "unknown"
vector = get_word_vector(word)
print(f"Embedding for '{word}':", vector)  # Returns zeros


Vocabulary: {'i': 0, 'love': 1, 'machine': 2, 'learning': 3, 'is': 4, 'amazing': 5, 'new': 6, 'things': 7}
Embedding Matrix E:
 [[0.06588461 0.91788597 0.67036757]
 [0.4        0.5        0.6       ]
 [0.1        0.2        0.3       ]
 [0.2        0.3        0.4       ]
 [0.10699154 0.25140772 0.76108001]
 [0.3        0.4        0.5       ]
 [0.80456922 0.20992905 0.0958829 ]
 [0.08965483 0.58516625 0.82310121]]
Embedding for 'machine': [0.1 0.2 0.3]
Embedding for 'i': [0.06588461 0.91788597 0.67036757]
Embedding for 'unknown': [0. 0. 0.]


In [8]:
import numpy as np

def create_one_hot_encodings(corpus):
    # Preprocessing
    vocabulary = {}
    index = 0
    for sentence in corpus:
        words = sentence.lower().split()
        for word in words:
            if word not in vocabulary:
                vocabulary[word] = index
                index += 1

    V = len(vocabulary)

    # Initialize one-hot encoding matrix
    one_hot_encodings = {}
    for word, idx in vocabulary.items():
        one_hot_vector = np.zeros(V)
        one_hot_vector[idx] = 1
        one_hot_encodings[word] = one_hot_vector

    return vocabulary, one_hot_encodings

# Example usage:
corpus = [
    "I love machine learning",
    "Machine learning is amazing",
    "I love learning new things"
]

vocabulary, one_hot_encodings = create_one_hot_encodings(corpus)

print("Vocabulary:", vocabulary)
print("\nOne-Hot Encodings:")
for word, one_hot_vector in one_hot_encodings.items():
    print(f"Word: '{word}' - One-Hot Vector: {one_hot_vector}")


Vocabulary: {'i': 0, 'love': 1, 'machine': 2, 'learning': 3, 'is': 4, 'amazing': 5, 'new': 6, 'things': 7}

One-Hot Encodings:
Word: 'i' - One-Hot Vector: [1. 0. 0. 0. 0. 0. 0. 0.]
Word: 'love' - One-Hot Vector: [0. 1. 0. 0. 0. 0. 0. 0.]
Word: 'machine' - One-Hot Vector: [0. 0. 1. 0. 0. 0. 0. 0.]
Word: 'learning' - One-Hot Vector: [0. 0. 0. 1. 0. 0. 0. 0.]
Word: 'is' - One-Hot Vector: [0. 0. 0. 0. 1. 0. 0. 0.]
Word: 'amazing' - One-Hot Vector: [0. 0. 0. 0. 0. 1. 0. 0.]
Word: 'new' - One-Hot Vector: [0. 0. 0. 0. 0. 0. 1. 0.]
Word: 'things' - One-Hot Vector: [0. 0. 0. 0. 0. 0. 0. 1.]


In [9]:
def generate_skip_gram_pairs(sentences, window_size):
    # Preprocessing: Build the vocabulary and word indices
    vocabulary = {}
    index = 0
    for sentence in sentences:
        words = sentence.lower().split()
        for word in words:
            if word not in vocabulary:
                vocabulary[word] = index
                index += 1

    # Generate skip-gram training pairs
    training_pairs = []
    for sentence in sentences:
        words = sentence.lower().split()
        for i, target_word in enumerate(words):
            # Define the context window
            start = max(0, i - window_size)
            end = min(len(words), i + window_size + 1)
            for j in range(start, end):
                if i != j:
                    context_word = words[j]
                    training_pairs.append((target_word, context_word))

    return vocabulary, training_pairs

# Example usage:
sentences = [
    "I love machine learning",
    "Machine learning is amazing",
    "I love learning new things"
]
window_size = 2
vocabulary, training_pairs = generate_skip_gram_pairs(sentences, window_size)

print("Vocabulary:", vocabulary)
print("\nSkip-Gram Training Pairs:")
for pair in training_pairs:
    print(pair)


Vocabulary: {'i': 0, 'love': 1, 'machine': 2, 'learning': 3, 'is': 4, 'amazing': 5, 'new': 6, 'things': 7}

Skip-Gram Training Pairs:
('i', 'love')
('i', 'machine')
('love', 'i')
('love', 'machine')
('love', 'learning')
('machine', 'i')
('machine', 'love')
('machine', 'learning')
('learning', 'love')
('learning', 'machine')
('machine', 'learning')
('machine', 'is')
('learning', 'machine')
('learning', 'is')
('learning', 'amazing')
('is', 'machine')
('is', 'learning')
('is', 'amazing')
('amazing', 'learning')
('amazing', 'is')
('i', 'love')
('i', 'learning')
('love', 'i')
('love', 'learning')
('love', 'new')
('learning', 'i')
('learning', 'love')
('learning', 'new')
('learning', 'things')
('new', 'love')
('new', 'learning')
('new', 'things')
('things', 'learning')
('things', 'new')


In [10]:
def generate_cbow_pairs(sentences, window_size):
    # Preprocessing: Build the vocabulary and word indices
    vocabulary = {}
    index = 0
    for sentence in sentences:
        words = sentence.lower().split()
        for word in words:
            if word not in vocabulary:
                vocabulary[word] = index
                index += 1

    # Generate CBOW training pairs
    training_pairs = []
    for sentence in sentences:
        words = sentence.lower().split()
        for i, target_word in enumerate(words):
            # Define the context window
            start = max(0, i - window_size)
            end = min(len(words), i + window_size + 1)
            context_words = []
            for j in range(start, end):
                if i != j:
                    context_words.append(words[j])
            if context_words:
                training_pairs.append((tuple(context_words), target_word))

    return vocabulary, training_pairs

# Example usage:
sentences = [
    "I love machine learning",
    "Machine learning is amazing",
    "I love learning new things"
]
window_size = 2
vocabulary, training_pairs = generate_cbow_pairs(sentences, window_size)

print("Vocabulary:", vocabulary)
print("\nCBOW Training Pairs:")
for pair in training_pairs:
    print(f"Context: {pair[0]}, Target: {pair[1]}")


Vocabulary: {'i': 0, 'love': 1, 'machine': 2, 'learning': 3, 'is': 4, 'amazing': 5, 'new': 6, 'things': 7}

CBOW Training Pairs:
Context: ('love', 'machine'), Target: i
Context: ('i', 'machine', 'learning'), Target: love
Context: ('i', 'love', 'learning'), Target: machine
Context: ('love', 'machine'), Target: learning
Context: ('learning', 'is'), Target: machine
Context: ('machine', 'is', 'amazing'), Target: learning
Context: ('machine', 'learning', 'amazing'), Target: is
Context: ('learning', 'is'), Target: amazing
Context: ('love', 'learning'), Target: i
Context: ('i', 'learning', 'new'), Target: love
Context: ('i', 'love', 'new', 'things'), Target: learning
Context: ('love', 'learning', 'things'), Target: new
Context: ('learning', 'new'), Target: things


In [11]:
import numpy as np

def rnn_forward(x, Wxh, Whh, Why, bh, by, h0):
    h = h0
    hs = []
    ys = []
    for t in range(len(x)):
        xt = np.array([[x[t]]])  # Input at time t (make it a column vector)
        h = np.tanh(np.dot(Whh, h) + np.dot(Wxh, xt) + bh)  # Hidden state
        y = np.dot(Why, h) + by  # Output
        hs.append(h)
        ys.append(y)
    return ys, hs

# Example usage:
# Input sequence
x = [1, 2, 3]

# Hyperparameters
input_size = 1  # Since x is a sequence of numbers
hidden_size = 4  # You can choose any size for the hidden state
output_size = 1  # Output is a single number at each time step

# Random initialization of weights and biases
np.random.seed(0)  # For reproducibility
Wxh = np.random.randn(hidden_size, input_size) * 0.01
Whh = np.random.randn(hidden_size, hidden_size) * 0.01
Why = np.random.randn(output_size, hidden_size) * 0.01
bh = np.zeros((hidden_size, 1))
by = np.zeros((output_size, 1))
h0 = np.zeros((hidden_size, 1))

# Run the RNN forward function
ys, hs = rnn_forward(x, Wxh, Whh, Why, bh, by, h0)

print("Outputs at each time step:")
for t, y in enumerate(ys):
    print(f"Time step {t+1}: y = {y.flatten()}")


Outputs at each time step:
Time step 1: y = [-0.00050584]
Time step 2: y = [-0.00101643]
Time step 3: y = [-0.00152624]


In [13]:
import numpy as np

def softmax(x, axis=-1):
    """Compute the softmax of each element along the specified axis of x."""
    exp_x = np.exp(x - np.max(x, axis=axis, keepdims=True))  # For numerical stability
    return exp_x / np.sum(exp_x, axis=axis, keepdims=True)

def self_attention(X, Wq, Wk, Wv):

    # Compute Queries (Q), Keys (K), and Values (V)
    Q = np.dot(X, Wq)  # Shape: (n, dout)
    K = np.dot(X, Wk)  # Shape: (n, dout)
    V = np.dot(X, Wv)  # Shape: (n, dout)

    # Compute attention scores: Q * K.T, then scale by sqrt(dout)
    d_k = Q.shape[1]  # dout
    attention_scores = np.dot(Q, K.T) / np.sqrt(d_k)  # Shape: (n, n)

    # Apply softmax to attention scores
    attention_weights = softmax(attention_scores, axis=-1)  # Shape: (n, n)

    # Compute final output: Attention weights * V
    output = np.dot(attention_weights, V)  # Shape: (n, dout)

    return output

# Example usage:
np.random.seed(0)  # For reproducibility

# Input matrix X (n=4 vectors, d=3 features per vector)
X = np.random.rand(4, 3)  # Shape: (4, 3)

# Learnable weight matrices Wq, Wk, Wv
d = 3  # Input dimension
dout = 2  # Output dimension
Wq = np.random.rand(d, dout)  # Shape: (3, 2)
Wk = np.random.rand(d, dout)  # Shape: (3, 2)
Wv = np.random.rand(d, dout)  # Shape: (3, 2)

# Call the self_attention function
output = self_attention(X, Wq, Wk, Wv)

print("Input Matrix X:")
print(X)
print("\nWeight Matrix Wq:")
print(Wq)
print("\nWeight Matrix Wk:")
print(Wk)
print("\nWeight Matrix Wv:")
print(Wv)
print("\nSelf-Attention Output:")
print(output)


Input Matrix X:
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]
 [0.38344152 0.79172504 0.52889492]]

Weight Matrix Wq:
[[0.56804456 0.92559664]
 [0.07103606 0.0871293 ]
 [0.0202184  0.83261985]]

Weight Matrix Wk:
[[0.77815675 0.87001215]
 [0.97861834 0.79915856]
 [0.46147936 0.78052918]]

Weight Matrix Wv:
[[0.11827443 0.63992102]
 [0.14335329 0.94466892]
 [0.52184832 0.41466194]]

Self-Attention Output:
[[0.53569849 1.29450415]
 [0.53551973 1.29413435]
 [0.53849796 1.29925955]
 [0.53131543 1.28657939]]
